### ISSUE TITLE
Will this be updated for sunbreak skills?

### ISSUE THREAD

**Issue by Sera9145** [chanleyou/mhr-damage-calculator#2]
Like the title says, will the new sunbreak skills like Dereliction, chain crit etc be added at some point?

**Comment by chanleyou** [comment]
I'm currently working on a new all-in-one calculator + set builder for Sunbreak at https://github.com/chanleyou/sunbreak-calculator, it can be found at: https://sunbreak-calculator.netlify.app/

Not all the new skills work yet as there are a whole bunch of tiny interactions which are a pain to code (red vs blue scroll, qurio stacks, chain crit stacks etc) but I'm slowly working on it
